---
local_db: sqlite3:/var/vcap/services/insight/insight_node.db
base_dir: /var/vcap/services/insight/
insight_ctl: rabbitmqctl
insight_server: rabbitmq-server
insight_port: 5672
mbus: nats://localhost:4222
index: 0
log_level: DEBUG
local_ip: 127.0.0.1
available_memory: 4096
max_memory: 16
node_id: insight_node_1
pid: /var/vcap/sys/run/insight_node.pid
migration_nfs: /mnt/appcloud
